# Generated by Django 4.2.4 on 2023-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('token_uri', models.CharField(max_length=500)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('scopes', models.CharField(max_length=500)),
            ],
        ),
    ]
