# Generated by Django 4.2.4 on 2023-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
