# Generated by Django 4.2.4 on 2023-08-27 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_googlecredentials_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=400, null=True)),
                ('source', models.CharField(max_length=40, null=True)),
                ('source_file_id', models.CharField(max_length=400, null=True)),
                ('mime_type', models.CharField(max_length=400, null=True)),
                ('file_content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
