# Generated by Django 4.2.4 on 2023-08-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files_googlecredentials_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='client_id',
            field=models.CharField(default=0, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='client_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
