# Generated by Django 4.2.4 on 2023-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_files_client_id_alter_googlecredentials_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='client_id',
            field=models.CharField(max_length=500),
        ),
    ]
