# Generated by Django 4.2.4 on 2023-08-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_files_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=500)),
                ('file_id', models.CharField(max_length=500)),
            ],
        ),
    ]
